<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Sabium\Handler\CreatePessoa::class => Sabium\Handler\CreatePessoaFactory::class,
            Sabium\Handler\DeletePessoaHandler::class => Sabium\Handler\DeletePessoaHandlerFactory::class,
            Sabium\Handler\PessoaHandler::class => Sabium\Handler\PessoaHandlerFactory::class,
            Sabium\Handler\RetriveIdadePessoa::class => Sabium\Handler\RetriveIdadePessoaFactory::class,
            Sabium\Handler\UpdatePessoaHandler::class => Sabium\Handler\UpdatePessoaHandlerFactory::class,
            Sabium\Middleware\PessoaBodyValidator::class => Sabium\Middleware\PessoaBodyValidatorFactory::class,
            Sabium\Middleware\PessoaEndpointValidator::class => Sabium\Middleware\PessoaEndpointValidatorFactory::class,
        ],
    ],
];
